include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: info

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
    - prefer_single_quotes
